### ISSUE TITLE
UNABLE_TO_PARSE_LINE error

### ISSUE THREAD

**Issue by ddimitrioglo** [lifeomic/terraform-plan-parser#4]
I'm trying to parse following output:

```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

+ aws_iam_role.terraform_demo
      id:                    <computed>
      arn:                   <computed>
      assume_role_policy:    "{\n \"Version\": \"2012-10-17\",\n \"Statement\": [\n   {\n     \"Action\": \"sts:AssumeRole\",\n     \"Principal\": {\n       \"Service\": \"ec2.amazonaws.com\"\n     },\n     \"Effect\": \"Allow\",\n     \"Sid\": \"\"\n   }\n ]\n}\n"
      create_date:           <computed>
      description:           "test IAM role"
      force_detach_policies: "false"
      name:                  "terraform_demo"
      path:                  "/"
      unique_id:             <computed>
Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: xxx/iam/terraform.tfstate.d/default/terraform.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "xxx/iam/terraform.tfstate.d/default/terraform.tfplan"
```

and getting following output:

```json
{
    "errors": [
        {
            "code": "UNABLE_TO_PARSE_LINE",
            "message": "Unable to parse \"+ aws_iam_role.terraform_demo\" (ignoring)"
        },
        {
            "code": "ORPHAN_ATTRIBUTE_LINE",
            "message": "Attribute line \"      id:                    <computed>\" is not associated with a data source or resource (ignoring)"
        },
        {
            "code": "ORPHAN_ATTRIBUTE_LINE",
            "message": "Attribute line \"      arn:                   <computed>\" is not associated with a data source or resource (ignoring)"
        },
        {
            "code": "ORPHAN_ATTRIBUTE_LINE",
            "message": "Attribute line \"      assume_role_policy:    \"{\\n \\\"Version\\\": \\\"2012-10-17\\\",\\n \\\"Statement\\\": [\\n   {\\n     \\\"Action\\\": \\\"sts:AssumeRole\\\",\\n     \\\"Principal\\\": {\\n       \\\"Service\\\": \\\"ec2.amazonaws.com\\\"\\n     },\\n     \\\"Effect\\\": \\\"Allow\\\",\\n     \\\"Sid\\\": \\\"\\\"\\n   }\\n ]\\n}\\n\"\" is not associated with a data source or resource (ignoring)"
        },
        {
            "code": "ORPHAN_ATTRIBUTE_LINE",
            "message": "Attribute line \"      create_date:           <computed>\" is not associated with a data source or resource (ignoring)"
        },
        {
            "code": "ORPHAN_ATTRIBUTE_LINE",
            "message": "Attribute line \"      description:           \"test IAM role\"\" is not associated with a data source or resource (ignoring)"
        },
        {
            "code": "ORPHAN_ATTRIBUTE_LINE",
            "message": "Attribute line \"      force_detach_policies: \"false\"\" is not associated with a data source or resource (ignoring)"
        },
        {
            "code": "ORPHAN_ATTRIBUTE_LINE",
            "message": "Attribute line \"      name:                  \"terraform_demo\"\" is not associated with a data source or resource (ignoring)"
        },
        {
            "code": "ORPHAN_ATTRIBUTE_LINE",
            "message": "Attribute line \"      path:                  \"/\"\" is not associated with a data source or resource (ignoring)"
        },
        {
            "code": "ORPHAN_ATTRIBUTE_LINE",
            "message": "Attribute line \"      unique_id:             <computed>\" is not associated with a data source or resource (ignoring)"
        }
    ],
    "changedResources": [],
    "changedDataSources": []
}
```

any suggestions? 

Thanks!

**Comment by philidem** [comment]
What version of `terraform` are you using? In the latest version, the lines are suppose to start with one of these sequences:

```js
'  +'
'  -'
'-/+'
'  ~'
' <='
```

Your code has sequence `'+ '` which is slightly different. I am guessing this is something that changed in terraform at some point.

I can try to adjust the parser to be backwards compatible with this output but want to make sure I understand how the output is formatted in old versions.

**Comment by philidem** [comment]
I published `terraform-plan-parser@1.1.0` which makes parsing of the action (create, destroy, replace, update, and read) more lenient. As long as there are no other major changes in the output, this should fix the problem that you had seen.

See https://github.com/lifeomic/terraform-plan-parser/commit/bbf73c4171a9d16a0cd1ef48ac2859d100126ae9

Please let me know if this fixes the issue.

**Comment by ddimitrioglo** [comment]
@philidem I'm using `0.10.4` version of terraform. Will upgrade `terraform-plan-parser` and come with updates if issues is still reproducing.

**Comment by ddimitrioglo** [comment]
Confirm that it fixed in `terraform-plan-parser@1.1.0`

```
{
    "errors": [],
    "changedResources": [
        {
            "action": "create",
            "type": "s_iam_role",
            "name": "terraform_demo",
            "changedAttributes": {
                "id": {
                    "new": {
                        "type": "computed"
                    }
                },
                "arn": {
                    "new": {
                        "type": "computed"
                    }
                },
                "assume_role_policy": {
                    "new": {
                        "type": "string",
                        "value": "{\n \"Version\": \"2012-10-17\",\n \"Statement\": [\n   {\n     \"Action\": \"sts:AssumeRole\",\n     \"Principal\": {\n       \"Service\": \"ec2.amazonaws.com\"\n     },\n     \"Effect\": \"Allow\",\n     \"Sid\": \"\"\n   }\n ]\n}\n"
                    }
                },
                "create_date": {
                    "new": {
                        "type": "computed"
                    }
                },
                "description": {
                    "new": {
                        "type": "string",
                        "value": "test IAM role"
                    }
                },
                "force_detach_policies": {
                    "new": {
                        "type": "string",
                        "value": "false"
                    }
                },
                "name": {
                    "new": {
                        "type": "string",
                        "value": "terraform_demo"
                    }
                },
                "path": {
                    "new": {
                        "type": "string",
                        "value": "/"
                    }
                },
                "unique_id": {
                    "new": {
                        "type": "computed"
                    }
                }
            }
        }
    ],
    "changedDataSources": []
}
```

Thanks!

**Comment by ddimitrioglo** [comment]
Hi @philidem,

After some additional testing I've noticed that resource type is parsed incorrectly `s_iam_role` instead of `aws_iam_role`

**Comment by philidem** [comment]
Sorry about! I revised the test case and fixed the code. I just published `terraform-plan-parser@1.1.2`. Please let me know if that works for real this time. Thanks!
